### ISSUE TITLE
Remove "loading" texts

### ISSUE THREAD

**Issue by armanddidierjean** [aeecleclair/CalypSSO#47]
Maybe use a skeleton, or an empty component

**Comment by Marc-Andrieu** [comment]
https://github.com/user-attachments/assets/728a7011-46ea-4bbb-a1e4-588cfc60c25d

**Comment by Marc-Andrieu** [comment]
When the page is loading, there are:
* 0 textboxes
* and 8 "Loading...".

In the login page:
* the textboxes, and only them, are wrapped in a classical `<Suspense>` tag: displayed as nothing when loading, then rendered as two textboxes -> here a skeleton would be appropriate
* and there are also 8 `<SuspenseHiddenField>` tags: displayed as "Loading..." (see `<SuspenseEmbed>`), then rendered as nothing -> why showing some "Loading..." on kind of query parameters that are not meant to be rendered?

So I think:
* `<SuspenseHiddenField>` should definitely have an empty fallback (locally it works for me: no "Loading..." anymore)
  * The "Loading..." text is in `<SuspenseEmbed>`, on which also depends `<SuspenseConditional>` which has a single occurrence: should we delete `<SuspenseEmbed>` and have to independent custom components for suspense, or empty the fallback of `<SuspenseEmbed>` attr anyway?
* A skeleton for the textboxes is welcome to preserve the height of the `<CenteredCard>`.
